BinarySearch: BinarySearch.cpp
	g++ -o BinarySearch.out BinarySearch.cpp

tiny: BinarySearch
	./BinarySearch.out tinyAllowlist.txt < tinyText.txt

large: BinarySearch
	./BinarySearch.out largeAllowlist.txt < largeText.txt
